assets:
  sources:
    - assets/events
    - assets/img
  destination: /assets/img
  plugins:
    img:
      optim:
        verbose: true
        pack: true
        allow_lossy: true
        advpng:
          level: 4
        jhead: true
        jpegoptim:
          allow_lossy: true
          strip: false
        jpegrecompress:
          allow_lossy: true
          quality: 2
        jpegtran:
          jpegrescan: false
        optipng:
          level: 7
          interlace: nil
        pngcrush:
          fix: true
        pngquant:
          allow_lossy: true
          speed: 1

collections:
  events:
    output: true

defaults:
  - scope:
      type: events
    values:
      layout: event
      navSection: Veranstaltungen
  - scope:
      path: ''
    values:
      layout: wide

exclude:
  - .idea/
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
